FROM nginx

COPY ./infra/config/sites-enabled /etc/nginx/sites-enabled
COPY ./infra/config/sites-enabled /etc/nginx/sites-available
COPY ./infra/config/includes /etc/nginx/includes
COPY ./infra/config/nginx.conf /etc/nginx/nginx.conf